<?php
/**
 * Title: Feature Marquee
 * Slug: marquee
 * Categories: feature
 */
?>
<!-- wp:group {"align":"wide","style":{"position":{"all":"relative"},"zIndex":{"all":"1"},"spacing":{"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained","contentSize":""}} -->
<div class="wp-block-group alignwide" style="margin-top:0;margin-bottom:0"><!-- wp:group {"align":"full","style":{"u002du002dmarquee-speed-mobile":"100s","u002du002dmarquee-speed-desktop":"120s","u002du002dmarquee-direction":"forwards","u002du002dmarquee-pause":"paused","spacing":{"blockGap":"var:preset|spacing|xs","margin":{"top":"0"}},"\u002d\u002dmarquee-speed-mobile":"100s","\u002d\u002dmarquee-speed-desktop":"100s","\u002d\u002dmarquee-direction":"reverse","\u002d\u002dmarquee-pause":"paused"},"layout":{"type":"flex","flexWrap":"nowrap","orientation":"marquee","justifyContent":"center"},"speedMobile":"100","speedDesktop":"100","reverse":true,"pauseOnHover":true,"fadeEdges":true} -->
<div class="wp-block-group alignfull fade-horizontal" style="margin-top:0;--marquee-speed-mobile:100s;--marquee-speed-desktop:100s;--marquee-direction:reverse;--marquee-pause:paused"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xs","margin":{"top":"0","bottom":"0"},"padding":{"top":"var:preset|spacing|lg","bottom":"var:preset|spacing|lg"}},"typography":{"fontStyle":"normal","fontWeight":"500"}},"layout":{"type":"flex","flexWrap":"nowrap","orientation":"horizontal","justifyContent":"center"},"fontSize":"16"} -->
<div class="wp-block-group has-16-font-size" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--lg);padding-bottom:var(--wp--preset--spacing--lg);font-style:normal;font-weight:500"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"var:preset|spacing|xxs","right":"var:preset|spacing|xs","bottom":"var:preset|spacing|xxs","left":"var:preset|spacing|xxs"}},"border":{"radius":"60px"}},"backgroundColor":"neutral-100","className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group is-style-default has-neutral-100-background-color has-background" style="border-radius:60px;padding-top:var(--wp--preset--spacing--xxs);padding-right:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xxs);padding-left:var(--wp--preset--spacing--xxs)"><!-- wp:image {"style":{"border":{"radius":"99px"},"spacing":{"padding":{"top":"0.5em","right":"0.5em","bottom":"0.5em","left":"0.5em"}}},"className":"is-style-icon","backgroundColor":"neutral-50","textColor":"primary","iconName":"check","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image has-custom-border is-style-icon has-primary-color has-neutral-50-background-color has-text-color has-background" style="border-radius:99px;padding-top:0.5em;padding-right:0.5em;padding-bottom:0.5em;padding-left:0.5em;--wp--custom--icon--background:var(--wp--preset--color--neutral-50, currentColor);--wp--custom--icon--color:var(--wp--preset--color--primary,currentColor);--wp--custom--icon--padding:0.5em 0.5em 0.5em 0.5em;--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;<path d=&quot;m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z&quot;/&gt;</svg&gt;')"><img src="#" alt="" style="border-radius:99px"/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>AI Assistant</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"var:preset|spacing|xxs","right":"var:preset|spacing|xs","bottom":"var:preset|spacing|xxs","left":"var:preset|spacing|xxs"}},"border":{"radius":"60px"}},"backgroundColor":"neutral-100","className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group is-style-default has-neutral-100-background-color has-background" style="border-radius:60px;padding-top:var(--wp--preset--spacing--xxs);padding-right:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xxs);padding-left:var(--wp--preset--spacing--xxs)"><!-- wp:image {"style":{"border":{"radius":"99px"},"spacing":{"padding":{"top":"0.5em","right":"0.5em","bottom":"0.5em","left":"0.5em"}}},"className":"is-style-icon","backgroundColor":"neutral-50","textColor":"primary","iconName":"check","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image has-custom-border is-style-icon has-primary-color has-neutral-50-background-color has-text-color has-background" style="border-radius:99px;padding-top:0.5em;padding-right:0.5em;padding-bottom:0.5em;padding-left:0.5em;--wp--custom--icon--background:var(--wp--preset--color--neutral-50, currentColor);--wp--custom--icon--color:var(--wp--preset--color--primary,currentColor);--wp--custom--icon--padding:0.5em 0.5em 0.5em 0.5em;--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;<path d=&quot;m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z&quot;/&gt;</svg&gt;')"><img src="#" alt="" style="border-radius:99px"/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>Optimized Funnel</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"var:preset|spacing|xxs","right":"var:preset|spacing|xs","bottom":"var:preset|spacing|xxs","left":"var:preset|spacing|xxs"}},"border":{"radius":"60px"}},"backgroundColor":"neutral-100","className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group is-style-default has-neutral-100-background-color has-background" style="border-radius:60px;padding-top:var(--wp--preset--spacing--xxs);padding-right:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xxs);padding-left:var(--wp--preset--spacing--xxs)"><!-- wp:image {"style":{"border":{"radius":"99px"},"spacing":{"padding":{"top":"0.5em","right":"0.5em","bottom":"0.5em","left":"0.5em"}}},"className":"is-style-icon","backgroundColor":"neutral-50","textColor":"primary","iconName":"check","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image has-custom-border is-style-icon has-primary-color has-neutral-50-background-color has-text-color has-background" style="border-radius:99px;padding-top:0.5em;padding-right:0.5em;padding-bottom:0.5em;padding-left:0.5em;--wp--custom--icon--background:var(--wp--preset--color--neutral-50, currentColor);--wp--custom--icon--color:var(--wp--preset--color--primary,currentColor);--wp--custom--icon--padding:0.5em 0.5em 0.5em 0.5em;--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;<path d=&quot;m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z&quot;/&gt;</svg&gt;')"><img src="#" alt="" style="border-radius:99px"/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>Increase Sales</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"var:preset|spacing|xxs","right":"var:preset|spacing|xs","bottom":"var:preset|spacing|xxs","left":"var:preset|spacing|xxs"}},"border":{"radius":"60px"}},"backgroundColor":"neutral-100","className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group is-style-default has-neutral-100-background-color has-background" style="border-radius:60px;padding-top:var(--wp--preset--spacing--xxs);padding-right:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xxs);padding-left:var(--wp--preset--spacing--xxs)"><!-- wp:image {"style":{"border":{"radius":"99px"},"spacing":{"padding":{"top":"0.5em","right":"0.5em","bottom":"0.5em","left":"0.5em"}}},"className":"is-style-icon","backgroundColor":"neutral-50","textColor":"primary","iconName":"check","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image has-custom-border is-style-icon has-primary-color has-neutral-50-background-color has-text-color has-background" style="border-radius:99px;padding-top:0.5em;padding-right:0.5em;padding-bottom:0.5em;padding-left:0.5em;--wp--custom--icon--background:var(--wp--preset--color--neutral-50, currentColor);--wp--custom--icon--color:var(--wp--preset--color--primary,currentColor);--wp--custom--icon--padding:0.5em 0.5em 0.5em 0.5em;--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;<path d=&quot;m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z&quot;/&gt;</svg&gt;')"><img src="#" alt="" style="border-radius:99px"/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>User Insights</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"var:preset|spacing|xxs","right":"var:preset|spacing|xs","bottom":"var:preset|spacing|xxs","left":"var:preset|spacing|xxs"}},"border":{"radius":"60px"}},"backgroundColor":"neutral-100","className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group is-style-default has-neutral-100-background-color has-background" style="border-radius:60px;padding-top:var(--wp--preset--spacing--xxs);padding-right:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xxs);padding-left:var(--wp--preset--spacing--xxs)"><!-- wp:image {"style":{"border":{"radius":"99px"},"spacing":{"padding":{"top":"0.5em","right":"0.5em","bottom":"0.5em","left":"0.5em"}}},"className":"is-style-icon","backgroundColor":"neutral-50","textColor":"primary","iconName":"check","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image has-custom-border is-style-icon has-primary-color has-neutral-50-background-color has-text-color has-background" style="border-radius:99px;padding-top:0.5em;padding-right:0.5em;padding-bottom:0.5em;padding-left:0.5em;--wp--custom--icon--background:var(--wp--preset--color--neutral-50, currentColor);--wp--custom--icon--color:var(--wp--preset--color--primary,currentColor);--wp--custom--icon--padding:0.5em 0.5em 0.5em 0.5em;--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;<path d=&quot;m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z&quot;/&gt;</svg&gt;')"><img src="#" alt="" style="border-radius:99px"/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>Lead Capture</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"var:preset|spacing|xxs","right":"var:preset|spacing|xs","bottom":"var:preset|spacing|xxs","left":"var:preset|spacing|xxs"}},"border":{"radius":"60px"}},"backgroundColor":"neutral-100","className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group is-style-default has-neutral-100-background-color has-background" style="border-radius:60px;padding-top:var(--wp--preset--spacing--xxs);padding-right:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xxs);padding-left:var(--wp--preset--spacing--xxs)"><!-- wp:image {"style":{"border":{"radius":"99px"},"spacing":{"padding":{"top":"0.5em","right":"0.5em","bottom":"0.5em","left":"0.5em"}}},"className":"is-style-icon","backgroundColor":"neutral-50","textColor":"primary","iconName":"check","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image has-custom-border is-style-icon has-primary-color has-neutral-50-background-color has-text-color has-background" style="border-radius:99px;padding-top:0.5em;padding-right:0.5em;padding-bottom:0.5em;padding-left:0.5em;--wp--custom--icon--background:var(--wp--preset--color--neutral-50, currentColor);--wp--custom--icon--color:var(--wp--preset--color--primary,currentColor);--wp--custom--icon--padding:0.5em 0.5em 0.5em 0.5em;--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;<path d=&quot;m16.7 7.1-6.3 8.5-3.3-2.5-.9 1.2 4.5 3.4L17.9 8z&quot;/&gt;</svg&gt;')"><img src="#" alt="" style="border-radius:99px"/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>Personalization</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->