<?php
/**
 * Title: Header Default
 * Slug: default
 * Categories: header
 * Block Types: core/template-part/header
 */
?>
<!-- wp:group {"align":"full","style":{"position":"","top":"","right":"","bottom":"","left":"","spacing":{"margin":{"top":"0","bottom":"0"}},"zIndex":""},"layout":{"type":"default"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0"><!-- wp:group {"align":"full","style":{"u002du002dmarquee-speed-mobile":"60s","u002du002dmarquee-speed-desktop":"90s","u002du002dmarquee-direction":"forwards","u002du002dmarquee-pause":"paused","typography":{"fontStyle":"normal","fontWeight":"500","lineHeight":"1"},"spacing":{"padding":{"top":"6px","bottom":"6px"},"margin":{"top":"0"},"blockGap":"var:preset|spacing|xxs"},"elements":{"link":{"color":{"text":"var:preset|color|base"}}},"color":{"text":"#feffff"}},"gradient":"primary","className":"is-style-default","layout":{"type":"constrained"},"fontSize":"12","speedMobile":"60","speedDesktop":"90","reverse":false,"pauseOnHover":true} -->
<div class="wp-block-group alignfull is-style-default has-primary-gradient-background has-text-color has-background has-link-color has-12-font-size" style="color:#feffff;margin-top:0;padding-top:6px;padding-bottom:6px;font-style:normal;font-weight:500;line-height:1"><!-- wp:group {"align":"wide","style":{"position":{"all":"relative"},"spacing":{"blockGap":"var:preset|spacing|xxs"}},"className":"is-style-default","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<div class="wp-block-group alignwide is-style-default"><!-- wp:paragraph {"style":{"spacing":{"padding":{"top":"3px","right":"6px","bottom":"3px","left":"6px"}},"typography":{"textTransform":"uppercase","fontSize":"10px","fontStyle":"normal","fontWeight":"800"},"border":{"radius":"15px","color":"#feffff","width":"1px"}}} -->
<p class="has-border-color" style="border-color:#feffff;border-width:1px;border-radius:15px;padding-top:3px;padding-right:6px;padding-bottom:3px;padding-left:6px;font-size:10px;font-style:normal;font-weight:800;text-transform:uppercase">SALE</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"typography":{"textDecoration":"none"},"elements":{"link":{"color":{"text":"#fffffffc"}}}},"className":""} -->
<p class="has-link-color" style="text-decoration:none">Display a site wide notice to your visitors here</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:group {"align":"full","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"blockGap":"0","padding":{"top":"var:preset|spacing|xs","bottom":"var:preset|spacing|xs"}},"position":{"all":"relative"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--xs);padding-bottom:var(--wp--preset--spacing--xs)"><!-- wp:group {"align":"wide","style":{"display":{"all":"grid"},"gridTemplateColumns":{"all":"repeat(12,minmax(0,1fr))"},"gridTemplateRows":{"all":"repeat(1,minmax(0,1fr))"},"gridColumnStart":"","gridColumnEnd":"","gridRowStart":"","gridRowEnd":""},"layout":{"type":"flex","orientation":"grid","justifyContent":"stretch"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"style":{"spacing":{"blockGap":"4px"},"zIndex":{"all":"0"},"width":{"all":""},"minWidth":{"all":"120px"},"gridColumnStart":{"all":"1","mobile":"1"},"gridColumnEnd":{"all":"3","mobile":"4"}},"layout":{"type":"flex","flexWrap":"nowrap"},"onclick":""} -->
<div class="wp-block-group"><!-- wp:pattern {"slug":"utility-logo","preview":true} /--></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"gridColumnStart":{"all":"3","mobile":"12"},"gridColumnEnd":{"all":"11","mobile":"13"},"gridRowStart":{"all":"1"},"gridRowEnd":{"all":"2"}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:navigation {"ref":"","icon":"menu","style":{"spacing":{"padding":{"top":"var:preset|spacing|xxs","bottom":"var:preset|spacing|xxs"}}}} /--></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0"},"\u002d\u002dflex-direction":"row-reverse","\u002d\u002dflex-direction-desktop":"row","gridColumnStart":{"all":"11","mobile":"9"},"gridColumnEnd":{"all":"13","mobile":"12"}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"right"},"onclick":""} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"right":"var:preset|spacing|xs","left":"var:preset|spacing|xs"}}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group" style="padding-right:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--xs)"><!-- wp:buttons {"style":{"position":{"all":"fixed"},"top":{"all":"20px"},"right":{"all":"20px"},"zIndex":{"all":"100"},"spacing":{"margin":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-buttons" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0"><!-- wp:button {"backgroundColor":"transparent","textColor":"neutral-900","style":{"spacing":{"blockGap":"0","padding":{"top":"6px","right":"6px","bottom":"6px","left":"6px"}},"boxShadow":{"hover":{"color":"#f6f6f9","inset":"inset","spread":"20"},"color":"transparent","inset":"inset","spread":"20"},"display":{"all":"none"}},"className":"search-close","fontSize":"14","onclick":"(() =\u003e {\n  const searchToggles = document.querySelectorAll('.search-toggle');\n  const searchCloses = document.querySelectorAll('.search-close');\n  const searchModals = document.querySelectorAll('.search-modal');\n\n  searchModals.forEach((search) =\u003e {\n    search.classList.add('has-display-none');\n  });\n\n  searchToggles.forEach((toggle) =\u003e {\n    toggle.classList.remove('has-display-none');\n    toggle.firstChild.classList.remove('has-display-none');\n  });\n\n  searchCloses.forEach((close) =\u003e {\n    close.classList.add('has-display-none');\n    close.parentElement.classList.add('has-display-none');\n  });\n})();\n","iconSet":"wordpress","iconName":"close","iconSize":"20px","iconPosition":"end","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022m13 11.8 6.1-6.3-1-1-6.1 6.2-6.1-6.2-1 1 6.1 6.3-6.5 6.7 1 1 6.5-6.6 6.5 6.6 1-1z\u0022/\u003e\u003c/svg\u003e"} /--></div>
<!-- /wp:buttons -->
<!-- wp:group {"align":"full","style":{"position":{"all":"fixed"},"top":{"all":"0px"},"right":{"all":"0px"},"bottom":{"all":"0px"},"left":{"all":"0px"},"zIndex":{"all":"99"},"width":{"all":"100vw"},"filter":{"blur":"16","backdrop":true},"maxWidth":{"all":"100vw"},"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"var:preset|spacing|sm","right":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm"}},"display":{"all":"none"}},"className":"search-modal","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center","verticalAlignment":"top"},"onclick":"\n"} -->
<div class="wp-block-group alignfull search-modal" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm);backdrop-filter:blur(16px)"><!-- wp:spacer {"height":"100vh","width":"0px","style":{"position":{"all":"absolute"},"top":{"all":"0px"},"right":{"all":"0px"},"bottom":{"all":"0px"},"left":{"all":"0px"},"filter":{"opacity":"50"},"layout":{"flexSize":"100vh","selfStretch":"fixed"}},"backgroundColor":"white"} -->
<div style="height:100vh;width:0px;filter:opacity(50%)" aria-hidden="true" class="wp-block-spacer has-white-background-color has-background"></div>
<!-- /wp:spacer -->
<!-- wp:group {"style":{"width":"","spacing":{"padding":{"top":"var:preset|spacing|xxl"},"margin":{"top":"0"}},"display":"","order":"","maxWidth":"","zIndex":{"all":"1"},"position":{"all":"relative"}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="margin-top:0;padding-top:var(--wp--preset--spacing--xxl)"><!-- wp:search {"label":"","showLabel":false,"placeholder":"Search this site","width":100,"widthUnit":"%","buttonText":"Search","buttonPosition":"button-inside","buttonUseIcon":true,"style":{"maxWidth":{"all":"90vw"},"width":{"all":"600px"}},"textColor":"currentColor"} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right","flexWrap":"nowrap"},"style":{"spacing":{"blockGap":"var:preset|spacing|xxs"},"position":"","top":"","right":"","bottom":"","left":"","zIndex":""}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"transparent","textColor":"neutral-800","style":{"spacing":{"blockGap":"0","padding":{"top":"4px","right":"4px","bottom":"4px","left":"4px"}},"boxShadow":{"hover":{"color":"#f6f6f9","inset":"inset","spread":"20"},"color":"transparent","inset":"inset","spread":"20"}},"className":"search-toggle","fontSize":"14","onclick":"(() =\u003e {\n  const searchCloses = document.querySelectorAll('.search-close');\n  const searchToggles = document.querySelectorAll('.search-toggle');\n  const searchModals = document.querySelectorAll('.search-modal');\n\n  searchModals.forEach((modal) =\u003e {\n    modal.classList.remove('has-display-none');\n  });\n\n  searchToggles.forEach((toggle) =\u003e {\n    toggle.classList.add('has-display-none');\n    toggle.firstChild.classList.add('has-display-none');\n  });\n\n  searchCloses.forEach((close) =\u003e {\n    close.classList.remove('has-display-none');\n    close.parentElement.classList.remove('has-display-none');\n  });\n})();\n","iconSet":"wordpress","iconName":"search","iconSize":"22px","iconPosition":"end","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022M13.5 6C10.5 6 8 8.5 8 11.5c0 1.1.3 2.1.9 3l-3.4 3 1 1.1 3.4-2.9c1 .9 2.2 1.4 3.6 1.4 3 0 5.5-2.5 5.5-5.5C19 8.5 16.5 6 13.5 6zm0 9.5c-2.2 0-4-1.8-4-4s1.8-4 4-4 4 1.8 4 4-1.8 4-4 4z\u0022/\u003e\u003c/svg\u003e"} /--></div>
<!-- /wp:buttons -->
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right","flexWrap":"nowrap"},"style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"transparent","textColor":"current","style":{"spacing":{"blockGap":"0","padding":{"top":"6px","right":"6px","bottom":"6px","left":"6px"}},"boxShadow":{"hover":{"color":"#f3f4f6","inset":"inset","spread":"22","blur":"0","y":"0","x":"0"},"color":"transparent","inset":"inset","spread":"22","blur":"0","x":"0","y":"0"}},"className":"hide-dark-mode is-style-fill","fontSize":"14","onclick":"( () =\u003e {\n\tdocument.body.classList.remove( 'is-style-light' );\n\tdocument.body.classList.add( 'is-style-dark' );\n\tdocument.cookie = 'blockifyDarkMode=true;path=/;max-age=86400';\n} )();","iconSet":"wordpress","iconName":"moon","iconSize":"22px","iconPosition":"end","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022M17.8 13.5c-2 .5-4.2 0-5.8-1.5s-2.1-3.8-1.5-5.8c.2-.6.4-1.1.7-1.7-.7.1-1.3.3-1.9.5-.9.4-1.8.9-2.6 1.7-2.9 2.9-2.9 7.7 0 10.6 2.9 2.9 7.7 2.9 10.6 0 .8-.8 1.3-1.6 1.7-2.6.2-.6.4-1.3.5-1.9-.5.3-1.1.6-1.7.7zm-1.5 2.7c-2.3 2.3-6.1 2.3-8.5 0-2.3-2.3-2.3-6.1 0-8.5.3-.3.7-.6 1-.8-.2 2.2.5 4.5 2.2 6.1s3.9 2.4 6.1 2.1c-.2.4-.5.8-.8 1.1z\u0022/\u003e\u003c/svg\u003e"} /-->
<!-- wp:button {"backgroundColor":"transparent","textColor":"current","style":{"spacing":{"blockGap":"0","padding":{"top":"6px","right":"6px","bottom":"6px","left":"6px"}},"boxShadow":{"hover":{"inset":"inset","color":"#f3f4f6","spread":"22","y":"0","x":"0","blur":"0"},"spread":"22","inset":"inset","color":"transparent","blur":"0","y":"0","x":"0"}},"className":"hide-light-mode is-style-fill","fontSize":"14","onclick":"( () =\u003e {\n\tdocument.body.classList.remove( 'is-style-dark' );\n\tdocument.body.classList.add( 'is-style-light' );\n\tdocument.cookie = 'blockifyDarkMode=false;path=/;max-age=86400';\n} )();","shadowPreset":"","shadowPresetHover":"","iconSet":"wordpress","iconName":"shadow","iconSize":"22px","iconPosition":"end","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022\u003e\u003cpath d=\u0022M12 8c-2.2 0-4 1.8-4 4s1.8 4 4 4 4-1.8 4-4-1.8-4-4-4zm0 6.5c-1.4 0-2.5-1.1-2.5-2.5s1.1-2.5 2.5-2.5 2.5 1.1 2.5 2.5-1.1 2.5-2.5 2.5zM12.8 3h-1.5v3h1.5V3zm-1.6 18h1.5v-3h-1.5v3zm6.8-9.8v1.5h3v-1.5h-3zm-12 0H3v1.5h3v-1.5zm9.7 5.6 2.1 2.1 1.1-1.1-2.1-2.1-1.1 1.1zM8.3 7.2 6.2 5.1 5.1 6.2l2.1 2.1 1.1-1.1zM5.1 17.8l1.1 1.1 2.1-2.1-1.1-1.1-2.1 2.1zM18.9 6.2l-1.1-1.1-2.1 2.1 1.1 1.1 2.1-2.1z\u0022/\u003e\u003c/svg\u003e"} /--></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right","flexWrap":"nowrap"},"style":{"spacing":{"blockGap":"var:preset|spacing|xxs"}}} -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"display":{"mobile":"none"},"typography":{"lineHeight":1.5}},"className":"is-hide-mobile nowrap is-style-fill","onclick":"","size":"small","iconSize":"20","iconPosition":"end"} -->
<div class="wp-block-button is-hide-mobile nowrap is-style-fill" style="line-height:1.5"><a class="wp-block-button__link wp-element-button">
						Sign Up
					</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->